#!/usr/bin/env node
// shared/build-themes.js — Compile themes/*.json → shared/css/themes.css
// No deps. Deterministic output (alpha sort) for byte-identite reproductible.
// Usage: node shared/build-themes.js

'use strict';

const fs = require('node:fs');
const path = require('node:path');

const ROOT = path.resolve(__dirname, '..');
const THEMES_DIR = path.join(ROOT, 'themes');
const OUT = path.join(__dirname, 'css', 'themes.css');
const VERSION = '2.66.1';

/**
 * Render a CSS block with alphabetically sorted properties.
 * Keys starting with '_' are ignored (comments/metadata).
 */
function renderBlock(selector, vars) {
    const keys = Object.keys(vars)
        .filter(k => !k.startsWith('_'))
        .sort();
    const lines = keys.map(k => `    ${k}: ${vars[k]};`);
    return `${selector} {\n${lines.join('\n')}\n}`;
}

function main() {
    // Read and sort all JSON theme files
    let files;
    try {
        files = fs.readdirSync(THEMES_DIR)
            .filter(f => f.endsWith('.json'))
            .sort();
    } catch (err) {
        console.error(`Error reading themes directory: ${THEMES_DIR}`);
        console.error(err.message);
        process.exit(1);
    }

    const blocks = [];
    let processedCount = 0;

    for (const f of files) {
        const filePath = path.join(THEMES_DIR, f);
        let theme;
        try {
            theme = JSON.parse(fs.readFileSync(filePath, 'utf8'));
        } catch (err) {
            console.error(`Error parsing ${f}: ${err.message}`);
            process.exit(1);
        }

        // msyx stays in :root of tokens.css — skip
        if (theme.name === 'msyx') continue;

        const dark = theme.modes && theme.modes.dark;
        const light = theme.modes && theme.modes.light;

        if (dark && Object.keys(dark).filter(k => !k.startsWith('_')).length > 0) {
            blocks.push(renderBlock(`[data-theme="${theme.name}"]`, dark));
        }
        if (light && Object.keys(light).filter(k => !k.startsWith('_')).length > 0) {
            blocks.push(renderBlock(`[data-theme="${theme.name}"][data-mode="light"]`, light));
        }

        processedCount++;
    }

    const header = [
        '/* AUTOGENERATED — do not edit. Source: themes/*.json. Run: node shared/build-themes.js */',
        `/* @ds-version: ${VERSION} */`,
        ''
    ].join('\n');

    const output = header + blocks.join('\n\n') + '\n';

    fs.writeFileSync(OUT, output, { encoding: 'utf8', flag: 'w' });
    console.log(`themes.css: ${blocks.length} blocks from ${processedCount} JSON file(s) (${files.length} total, msyx skipped)`);
}

main();
